# Generated by Django 4.1.4 on 2024-03-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name')},
        ),
    ]
