# Generated by Django 4.1.4 on 2023-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_teacher_salary_alter_teacher_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
