# Generated by Django 4.1.4 on 2023-07-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_class_time_class_end_time_class_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
    ]
