# Generated by Django 4.1.4 on 2023-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='player_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
