# Generated by Django 4.1.4 on 2023-07-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_school_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
