# Generated by Django 4.1.4 on 2023-08-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
