# Generated by Django 4.1.4 on 2023-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_student_average_grade_alter_student_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skill',
            field=models.IntegerField(blank=True, choices=[(1, 'Lecturer'), (2, 'Senior Lecturer'), (3, 'Assistant Professor'), (3, 'Associate Professor'), (4, 'Professor')], default=1, null=True),
        ),
    ]
