# Generated by Django 4.1.4 on 2023-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_teacher_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skill',
            field=models.CharField(blank=True, choices=[(1, 'Lecturer'), (2, 'Senior Lecturer'), (3, 'Assistant Professor'), (3, 'Associate Professor'), (4, 'Professor')], default=1, max_length=25, null=True),
        ),
    ]
