# Generated by Django 4.1.4 on 2023-08-11 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_teacher_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='money',
            field=models.IntegerField(blank=True, default=500000, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AddField(
            model_name='school',
            name='tuition',
            field=models.IntegerField(blank=True, default=10000, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
